In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel('2018.xls',dtype={'社保卡号':str})
df.head(5)

             购药时间           社保卡号    商品编码     商品名称  销售数量   应收金额    实收金额
0  2018-01-01 星期五      001616528  236701  强力VC银翘片     6   82.8   69.00
1  2018-01-02 星期六      001616528  236701  清热解毒口服液     1   28.0   24.64
2  2018-01-06 星期三     0012602828  236701       感康     2   16.8   15.00
3  2018-01-11 星期一  0010070343428  236701    三九感冒灵     1   28.0   28.00
4  2018-01-15 星期五    00101554328  236701    三九感冒灵     8  224.0  208.00

In [3]:
df[df.isna().any(axis=1)] # 查看所有有缺失值的行

                购药时间        社保卡号     商品编码 商品名称  销售数量  应收金额   实收金额
6570             NaN  0011778628  2367011  高特灵    10  56.0  56.00
6571  2018-04-25 星期二         NaN  2367011  高特灵     2  11.2   9.86

In [4]:
df.rename({'购药时间':'销售时间'},axis=1,inplace=True)
df.dropna(subset=['销售时间','社保卡号'],how='any',inplace=True) # 删除指定列的空值
df.reset_index(drop=True,inplace=True)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6575 entries, 0 to 6574
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   销售时间    6575 non-null   object
 1   社保卡号    6575 non-null   object
 2   商品编码    6575 non-null   int64
 3   商品名称    6575 non-null   object
 4   销售数量    6575 non-null   int64
 5   应收金额    6575 non-null   float64
 6   实收金额    6575 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 359.7+ KB

In [5]:
df['星期'] = df['销售时间'].str[11:]
df['销售时间'] = df['销售时间'].str[0:10]

In [6]:
df['销售时间'] = pd.to_datetime(df['销售时间'], errors='coerce') # 日期出错，返回nan
df.dropna(how='any',inplace=True)
df.reset_index(drop=True,inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6552 entries, 0 to 6551
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   销售时间    6552 non-null   datetime64[ns]
 1   社保卡号    6552 non-null   object
 2   商品编码    6552 non-null   int64
 3   商品名称    6552 non-null   object
 4   销售数量    6552 non-null   int64
 5   应收金额    6552 non-null   float64
 6   实收金额    6552 non-null   float64
 7   星期      6552 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(2), object(3)
memory usage: 409.6+ KB

In [7]:
df['商品编码'] = df['商品编码'].astype('str')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6552 entries, 0 to 6551
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   销售时间    6552 non-null   datetime64[ns]
 1   社保卡号    6552 non-null   object
 2   商品编码    6552 non-null   object
 3   商品名称    6552 non-null   object
 4   销售数量    6552 non-null   int64
 5   应收金额    6552 non-null   float64
 6   实收金额    6552 non-null   float64
 7   星期      6552 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 409.6+ KB

In [8]:
# df[df['销售数量']<0]
df = df[df['销售数量']>0]
df.reset_index(drop=True,inplace=True)
df.describe()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6509 entries, 0 to 6508
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   销售时间    6509 non-null   datetime64[ns]
 1   社保卡号    6509 non-null   object
 2   商品编码    6509 non-null   object
 3   商品名称    6509 non-null   object
 4   销售数量    6509 non-null   int64
 5   应收金额    6509 non-null   float64
 6   实收金额    6509 non-null   float64
 7   星期      6509 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 406.9+ KB

In [9]:
## 删除重复值
df.drop_duplicates(inplace=True)
df

           销售时间           社保卡号     商品编码     商品名称  销售数量   应收金额    实收金额   星期
0    2018-01-01      001616528   236701  强力VC银翘片     6   82.8   69.00  星期五
1    2018-01-02      001616528   236701  清热解毒口服液     1   28.0   24.64  星期六
2    2018-01-06     0012602828   236701       感康     2   16.8   15.00  星期三
3    2018-01-11  0010070343428   236701    三九感冒灵     1   28.0   28.00  星期一
4    2018-01-15    00101554328   236701    三九感冒灵     8  224.0  208.00  星期五
...         ...            ...      ...      ...   ...    ...     ...  ...
6504 2018-04-27  0010060482828  2367011      高特灵     1    5.6    5.00  星期三
6505 2018-04-27    00107886128  2367011      高特灵    10   56.0   54.80  星期三
6506 2018-04-27  0010087865628  2367011      高特灵     2   11.2    9.86  星期三
6507 2018-04-27     0013406628  2367011      高特灵     1    5.6    5.00  星期三
6508 2018-04-28     0011926928  2367011      高特灵     2   11.2   10.00  星期四

[6509 rows x 8 columns]

In [11]:
df.sort_values('销售时间',inplace=True)
df.reset_index(drop=True,inplace=True)
df

,销售时间,社保卡号,商品编码,商品名称,销售数量,应收金额,实收金额,星期
0,2018-01-01,001616528,236701,强力VC银翘片,6,82.8,69.0,星期五
1,2018-01-01,0010616728,865099,硝苯地平片(心痛定),2,3.4,3.0,星期五
2,2018-01-01,0010015658428,861405,苯磺酸氨氯地平片(络活喜),2,69.0,62.0,星期五
3,2018-01-01,00101470528,236709,心痛定,4,179.2,159.2,星期五
4,2018-01-01,0010014289328,866851,缬沙坦分散片(易达乐),1,26.0,23.0,星期五
...,...,...,...,...,...,...,...,...
6504,2018-07-19,001616528,861516,替米沙坦片(美卡素),1,38.0,33.5,星期二
6505,2018-07-19,0010036734128,861519,厄贝沙坦片(安博维),2,65.0,57.6,星期二
6506,2018-07-19,00101409528,2367011,开博通,2,62.0,56.0,星期二
6507,2018-07-19,0010073979728,867485,G琥珀酸美托洛尔缓释片(倍他乐克),2,35.8,31.6,星期二
6508,2018-07-19,0010083859528,861519,厄贝沙坦片(安博维),2,65.0,57.6,星期二

# 月均消费次数

In [34]:
num = df['销售数量'].count()
start = df.iloc[0]['销售时间']
start
end = df.iloc[-1]['销售时间']
end
days = end-start
days
months = round(days/pd.Timedelta(days = 30),0)
months
count_months = num /months
count_months
num
print(f'共计消费{num}次')
print(f'一共{months}月')
print(f'月均消费{round(count_months,0)}次')

共计消费6509次
一共7.0月
月均消费930.0次

# 月均消费金额

In [39]:
money = sum(df['实收金额'])
money
money_months = money/months
print(f'月收入金额{round(money_months,2)}')

月收入金额43433.57

# 客单价

In [40]:
p = money/num
print(f'客单价为{round(p,2)}元')

客单价为46.71元